/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.cubeon.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.beans.BeanInfo;

import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.netbeans.cubeon.tasks.spi.TaskEditorProvider;
import org.netbeans.cubeon.tasks.spi.TaskEditorProvider.EditorAttributeHandler;
import org.netbeans.cubeon.tasks.spi.TaskElement;
import org.netbeans.cubeon.tasks.spi.TaskRepository;
import org.netbeans.cubeon.tasks.spi.TaskRepositoryType;
import org.netbeans.cubeon.ui.util.PaintUtils;
import org.openide.cookies.SaveCookie;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.util.Lookup;
import org.openide.util.lookup.Lookups;
import org.openide.util.lookup.ProxyLookup;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
final class TaskEditorTopComponent extends TopComponent {

    private static final String PREFERRED_ID = "TaskEditorTopComponent";
    private static final Color c = UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient");
    private static final Color start = new Color(255, 255, 255, 255);
    private static final Color end = new Color(255, 255, 255, 0);
    private static final RenderingHints hints;
    private final static GradientPaint GRADIENT_HEADER_LARGE = new GradientPaint(0, 0,
            Color.WHITE, 0, 33, c);
    private TaskElement element;
    private final EditorNode editorNode;
    

    static {
        hints = new RenderingHints(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);
        hints.put(RenderingHints.KEY_INTERPOLATION,
                RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        hints.put(RenderingHints.KEY_RENDERING,
                RenderingHints.VALUE_RENDER_QUALITY);


    }

    TaskEditorTopComponent(TaskElement element) {
        this.element = element;
        initComponents();

        Lookup lookup = element.getLookup();

        TaskEditorProvider editorProvider = lookup.lookup(TaskEditorProvider.class);
        final EditorAttributeHandler eah = editorProvider.createEditorAttributeHandler();

        setName(eah.getName());

        setIcon(eah.getImage());
        TaskRepository taskRepository = element.getTaskRepository();
        TaskRepositoryType repositoryType = taskRepository.getLookup().lookup(TaskRepositoryType.class);
        Node taskRepositoryNode = taskRepository.getLookup().lookup(Node.class);
        lblHeader.setIcon(new ImageIcon(taskRepositoryNode.getIcon(BeanInfo.ICON_MONO_16x16)));
        lblHeader.setText(eah.getDisplayName());
        base.add(eah.getComponent(), BorderLayout.CENTER);
        editorNode = new EditorNode(eah);
        setActivatedNodes(new Node[]{editorNode});
        eah.addChangeListener(editorNode);

    }

  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        header =         new JPanel() {

            private int count;

            /**
            * Paints a gradient in the background of this component
            */
            @Override
            protected void paintComponent(Graphics g) {
                int i = count++;
                Graphics2D g2 = (Graphics2D) g;

                g2.setPaint(GRADIENT_HEADER_LARGE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                RenderingHints oldHints = g2.getRenderingHints();
                g2.setRenderingHints(hints);

                float width = getWidth();
                float height = getHeight();

                g2.translate(0, -30);

                PaintUtils.drawCurve(g2,
                    20.0f, -10.0f, 20.0f, -10.0f,
                    width / 2.0f - 40.0f, 10.0f,
                    0.0f, -5.0f,
                    width / 2.0f + 40, 1.0f,
                    0.0f, 5.0f,
                    50.0f, 5.0f, false,i,width,start,end );

                g2.translate(0, 30);
                g2.translate(0, height - 60);

                PaintUtils.drawCurve(g2,
                    30.0f, -15.0f, 50.0f, 15.0f,
                    width / 2.0f - 40.0f, 1.0f,
                    15.0f, -25.0f,
                    width / 2.0f, 1.0f / 2.0f,
                    0.0f, 25.0f,
                    15.0f, 9.0f, false, i, width, start, end);

                g2.translate(0, -height + 60);

                PaintUtils.drawCurve(g2,
                    height - 35.0f, -5.0f, height - 50.0f, 10.0f,
                    width / 2.0f - 40.0f, 1.0f,
                    height - 35.0f, -25.0f,
                    width / 2.0f, 1.0f / 2.0f,
                    height - 20.0f, 25.0f,
                    25.0f, 7.0f, true, i, width, start, end);

                g2.setRenderingHints(oldHints);
            }
        };
        javax.swing.JSeparator separator = new javax.swing.JSeparator();
        lblHeader = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        base.setBackground(new java.awt.Color(255, 255, 255));
        base.setLayout(new java.awt.BorderLayout());

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/cubeon/ui/repository.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lblHeader, "Task Element Name"); // NOI18N

        org.jdesktop.layout.GroupLayout headerLayout = new org.jdesktop.layout.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, separator, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
            .add(headerLayout.createSequentialGroup()
                .add(5, 5, 5)
                .add(lblHeader, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 443, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, headerLayout.createSequentialGroup()
                .add(lblHeader, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(separator, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        base.add(header, java.awt.BorderLayout.NORTH);

        add(base, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel base;
    private javax.swing.JPanel header;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables
    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER;
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    private class EditorNode extends AbstractNode implements ChangeListener, SaveCookie {

        private EditorAttributeHandler eah;

        public EditorNode(EditorAttributeHandler eah) {
            super(Children.LEAF);
            this.eah = eah;

        }

        @Override
        public String getName() {

            return eah.getName();
        }

        @Override
        public String getDisplayName() {
            return eah.getDisplayName();
        }

        @Override
        public String getShortDescription() {
            return getShortDescription();
        }

        public void stateChanged(ChangeEvent e) {


            getCookieSet().assign(SaveCookie.class, this);
        }

        public void save() throws IOException {
            throw new UnsupportedOperationException("Not supported yet.");
        }
    }
}
