/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.cubeon.ui;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.beans.BeanInfo;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.UIManager;
import org.netbeans.cubeon.tasks.spi.TaskElement;
import org.netbeans.cubeon.tasks.spi.TaskRepository;
import org.netbeans.cubeon.tasks.spi.TaskRepositoryType;
import org.openide.nodes.Node;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
final class TaskEditorTopComponent extends TopComponent {

    private static final String PREFERRED_ID = "TaskEditorTopComponent";

     TaskEditorTopComponent(TaskElement element) {
        initComponents();
        setName(element.getName());

        Lookup lookup = element.getLookup();
        associateLookup(lookup);
        Node node = lookup.lookup(Node.class);

        setIcon(node.getIcon(BeanInfo.ICON_MONO_16x16));
        TaskRepository taskRepository = element.getTaskRepository();
        TaskRepositoryType repositoryType = taskRepository.getLookup().lookup(TaskRepositoryType.class);
        Node taskRepositoryNode = taskRepository.getLookup().lookup(Node.class);
        lblHeader.setIcon(new ImageIcon(taskRepositoryNode.getIcon(BeanInfo.ICON_MONO_16x16)));
        lblHeader.setText(element.getName()); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        header =  new JPanel() {

            /**
            * Paints a gradient in the background of this component
            */
            @Override
            protected void paintComponent(Graphics g) {
                GradientPaint bgGradient =new GradientPaint(0, 0,
                    UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"), 0, (getHeight()/4)*3 , Color.WHITE);// background for the GUI
                ((Graphics2D) g).setPaint(bgGradient);
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        separator = new javax.swing.JSeparator();
        lblHeader = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        base.setBackground(new java.awt.Color(255, 255, 255));
        base.setLayout(new java.awt.BorderLayout());

        header.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/cubeon/ui/repository.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lblHeader, "Task Element Name"); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        base.add(header, java.awt.BorderLayout.NORTH);

        add(base, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel base;
    private javax.swing.JPanel header;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER;
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }
}
