/*
 *  Copyright 2009 Anuradha.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */

/*
 * TaskEditorUI.java
 *
 * Created on Jan 17, 2009, 2:38:18 PM
 */
package org.netbeans.cubeon.common.ui.internals;

import java.awt.BorderLayout;
import javax.swing.JComponent;
import org.netbeans.cubeon.common.ui.Group;
import org.netbeans.cubeon.common.ui.TaskEditor;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.event.DocumentListener;
import org.openide.util.NbBundle;

/**
 *
 * @author Anuradha
 */
public class TaskEditorUI extends javax.swing.JPanel implements TaskEditor {

    private final GroupView masterView;
    private GroupView detailView;

    /** Creates new form TaskEditorUI */
    public TaskEditorUI(GroupView groupView) {
        initComponents();
        pnlDetails.setVisible(false);
        pnlMaster.add(masterView = groupView, BorderLayout.CENTER);
    }

    public String getSummaryText() {
        return txtSummary.getText();
    }

    public void removeSummaryDocumentListener(DocumentListener listener) {
        txtSummary.getDocument().removeDocumentListener(listener);
    }

    public void addSummaryDocumentListener(DocumentListener listener) {
        txtSummary.getDocument().addDocumentListener(listener);
    }

    public void setCreatedDate(Date date) {
        final DateFormat dateFormat = SimpleDateFormat.getDateTimeInstance();
        String message = NbBundle.getMessage(TaskEditorUI.class,
                "TaskEditorUI.lblCreated.text", dateFormat.format(date));
        lblCreated.setText(message);
    }

    public void setUpdatedDate(Date date) {
        final DateFormat dateFormat = SimpleDateFormat.getDateTimeInstance();
        String message = NbBundle.getMessage(TaskEditorUI.class,
                "TaskEditorUI.lblUpdated.text", dateFormat.format(date));
        lblUpdated.setText(message);
    }

    public void setStatus(String status) {
        lblStatus.setText(NbBundle.getMessage(TaskEditorUI.class,
                "TaskEditorUI.lblStatus.text", status));
    }

    public void hideStatusLable(boolean b) {
        lblStatus.setVisible(!b);
    }

    public void hideUpdatedDateLable(boolean b) {
        lblUpdated.setVisible(!b);
    }

    public void hideCreatedDateLable(boolean b) {
        lblCreated.setVisible(!b);
    }

    public JComponent getComponent() {
        return this;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSummary = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        lblCreated = new javax.swing.JLabel();
        lblUpdated = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlMaster = new javax.swing.JPanel();
        pnlDetails = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        lblStatus.setForeground(new java.awt.Color(102, 102, 102));
        lblStatus.setText(NbBundle.getMessage(TaskEditorUI.class, "TaskEditorUI.lblStatus.text","-")); // NOI18N

        lblCreated.setForeground(new java.awt.Color(102, 102, 102));
        lblCreated.setText(NbBundle.getMessage(TaskEditorUI.class, "TaskEditorUI.lblCreated.text","-")); // NOI18N

        lblUpdated.setForeground(new java.awt.Color(102, 102, 102));
        lblUpdated.setText(NbBundle.getMessage(TaskEditorUI.class, "TaskEditorUI.lblUpdated.text","-")); // NOI18N

        jPanel1.setOpaque(false);

        pnlMaster.setOpaque(false);
        pnlMaster.setLayout(new java.awt.BorderLayout());

        pnlDetails.setOpaque(false);
        pnlDetails.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlMaster, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMaster, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
            .addComponent(pnlDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSummary, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCreated, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUpdated, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdated)
                    .addComponent(lblCreated)
                    .addComponent(lblStatus))
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCreated;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUpdated;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlMaster;
    private javax.swing.JTextField txtSummary;
    // End of variables declaration//GEN-END:variables

    public void setSummaryText(String summary) {
        txtSummary.setText(summary);
    }

    public void setMasterGroups(Group... groups) {
        masterView.clear();
        if (groups.length > 0) {
            for (Group group : groups) {
                masterView.addGroup(group);
            }
        }
    }

    public void setDetailGroups(Group... groups) {
        if (detailView != null) {
            detailView.clear();
        }
        if (groups.length > 0) {
            if (detailView == null) {
                detailView = new GroupView();
            }
            for (Group group : groups) {
                detailView.addGroup(group);
            }
            pnlDetails.add(detailView, BorderLayout.CENTER);
            pnlDetails.setVisible(true);
        } else {
            pnlDetails.setVisible(false);
        }
    }
}
