/*
 * AddEditTaskFolder.java
 *
 * Created on May 10, 2008, 12:04 PM
 */
package org.netbeans.cubeon.ui.dialogs;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import org.netbeans.cubeon.context.api.TaskFolder;
import org.openide.util.NbBundle;
import org.openide.util.Utilities;

/**
 *
 * @author  Anuradha G
 */
public class AddEditTaskFolder extends javax.swing.JPanel {

    private TaskFolder parent;

    /** Creates new form AddEditTaskFolder */
    private AddEditTaskFolder(TaskFolder parent) {
        this.parent = parent;
        initComponents();
    }

    public String getFolderName() {
        return txtName.getText().trim();
    }

    public void setFolderName(String name) {
        txtName.setText(name);
    }

    public String getFolderDescription() {
        return txtDescription.getText().trim();
    }

    public void setFolderDiescription(String descriptions) {
        txtDescription.setText(descriptions);
    }

    public JButton getOKButton() {
        return ok;
    }

    public static AddEditTaskFolder createAddUI(TaskFolder parent) {
        final AddEditTaskFolder aetf = new AddEditTaskFolder(parent);
        aetf.lblMainHeader.setText(NbBundle.getMessage(AddEditTaskFolder.class, "LBL_Add_Folder"));
        aetf.lblSubHeader.setText(NbBundle.getMessage(AddEditTaskFolder.class, "LBL_Add_Folder_Description"));
        aetf.lblIcon.setIcon(new ImageIcon(Utilities.loadImage("org/netbeans/cubeon/ui/dialogs/folder_add.png")));

        return aetf;
    }

    public static AddEditTaskFolder createEditUI(TaskFolder parent) {
        final AddEditTaskFolder aetf = new AddEditTaskFolder(parent);
        aetf.lblMainHeader.setText(NbBundle.getMessage(AddEditTaskFolder.class, "LBL_Edit_Folder"));
        aetf.lblSubHeader.setText(NbBundle.getMessage(AddEditTaskFolder.class, "LBL_Edit_Folder_Description"));
        aetf.lblIcon.setIcon(new ImageIcon(Utilities.loadImage("org/netbeans/cubeon/ui/dialogs/folder_edit.png")));

        return aetf;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ok = new javax.swing.JButton();
        pnlHeader = new javax.swing.JPanel();
        lblMainHeader = new javax.swing.JLabel();
        lblSubHeader = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        scrPane = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextPane();

        ok.setText(NbBundle.getMessage(AddEditTaskFolder.class, "AddEditTaskFolder.OK.text")); // NOI18N

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMainHeader.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblMainHeader.setText("_Main Header_"); // NOI18N

        lblSubHeader.setText("_description_"); // NOI18N

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMainHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(lblSubHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMainHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSubHeader)))
                .addContainerGap())
        );

        lblName.setText(org.openide.util.NbBundle.getMessage(AddEditTaskFolder.class, "AddEditTaskFolder.lblName.text")); // NOI18N

        lblDescription.setText(org.openide.util.NbBundle.getMessage(AddEditTaskFolder.class, "AddEditTaskFolder.lblDescription.text")); // NOI18N

        scrPane.setViewportView(txtDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPane, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName)
                .addGap(4, 4, 4)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrPane, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblMainHeader;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSubHeader;
    private javax.swing.JButton ok;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JScrollPane scrPane;
    private javax.swing.JTextPane txtDescription;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
